# provision_staging.yml
---
- name: Create ec2 instance
  hosts: all
  gather_facts: false
  tasks:
  - name: Create instance 
    ec2:
      key_name: awx-aws-keypair
      instance_type: "{{ instance_type }}" 
      image: "{{ ami_image }}"
      wait: yes
      wait_timeout: 360
      group: ansible-aws 
      instance_tags:
        type: awx-managed
      count_tag:
        type: awx-managed
      exact_count: 1
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes  
      region: "{{ region }}"
      termination_protection: yes
    register: ec2
  
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: myhosts 
      ansible_user: centos
    with_items: "{{ ec2.instances }}"
    when: ec2 is defined

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
    when: ec2 is defined